project:
  type: website
  output-dir: docs

website:
  title: "STAT545"
  back-to-top-navigation: true
  page-footer: "Copyright 2025, Grace Tompkins" 
  favicon: images/stat545_transparent.png 
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: " "
        icon: house-door-fill
      - sidebar:syllabus
      - sidebar:lectures_i
      - sidebar:lectures_ii
      - href: webpages/slides/slides.qmd
        text: "Slides"
      - href: webpages/worksheets.qmd
        text: "Worksheets"
      - sidebar:collabproj
      - sidebar:mda
      # - href: webpages/casestudies.qmd
      #   text: "Case Studies"
      - href: webpages/faq.qmd
        text: "FAQ"
        
    right:
      - href: "https://github.com/UBC-STAT/STAT545.github.io"
        icon: github
      - href: "https://youtube.com/playlist?list=PL32xpGMCWJAkihtosNGDQz0NP4UBqQnq8&si=VaWFgrlMNKHtgOHD"
        icon: youtube
        
  sidebar:
    - id: syllabus
      title: "Syllabus"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/syllabus/syllabusA.qmd
        - webpages/syllabus/syllabusB.qmd
  
                
        
    - id: lectures_i
      title: "Lectures (A)"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/lectures_i/lec1a_installation.qmd
        - webpages/lectures_i/lec1b_introR.qmd
        - webpages/lectures_i/lec2A_reproducibility.qmd
        - webpages/lectures_i/lec2b_versioncontrol.qmd
        - webpages/lectures_i/lec3_dplyr.qmd
        - webpages/lectures_i/lec4_datavis.qmd
        - webpages/lectures_i/lec5_tidydata.qmd
        - webpages/lectures_i/lec6a_modelfitting.qmd
        - webpages/lectures_i/lec6b_factorsanddates.qmd
        - webpages/lectures_i/lec7a_readwritedata.qmd
        - webpages/lectures_i/lec7b_joiningtibbles.qmd
        
    - id: lectures_ii
      title: "Lectures (B)"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/lectures_ii/lec8a_functions.qmd
        # - webpages/lectures_ii/lec8b_advfunctions.qmd
        # - webpages/lectures_ii/lec9_rpackages.qmd
        # - webpages/lectures_ii/lec10_shiny.qmd
        # - webpages/lectures_ii/lec11_automation.qmd
        # - webpages/lectures_ii/lec12_characterdata.qmd
        # - webpages/lectures_ii/lec13_listcolumns.qmd
        # - webpages/lectures_ii/lec14_quarto.qmd
        

        
    - id: collabproj
      title: "Collab Project"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/collabproj/collabproj_deliverable1.qmd
        - webpages/collabproj/collabproj_deliverable2.qmd
                
    - id: mda
      title: "Mini Data Analysis"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - webpages/mda/mda_deliverable1.qmd
        - webpages/mda/mda_deliverable2.qmd      
   
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



